apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.releaseName }}-secret
type: Opaque
data:
    {{- range $key, $value := .Values.global.secrets }}
    {{ $key }}: {{ $value | b64enc | quote }}
    {{- end }}
