apiVersion: v1
kind: Secret
metadata:
    name: samplesecret-{{ .Values.releaseName }}
type: Opaque
data:
  username:  {{ .Values.username }} #{{ .Values.username | b64enc | quote }}    
  password:  {{ .Values.password }} #{{ .Values.password | b64enc | quote }} 
  #   username: demoDev
  #  password: passwd
