apiVersion: ENC[AES256_GCM,data:KIk=,iv:rjeC+++bjczMBhISeGD9iXUdrH3xWroMQuiJMPa/xP0=,tag:sNJoV00oL9fTRsLxXsfDEQ==,type:str]
kind: ENC[AES256_GCM,data:FcHzIc6D,iv:6AwdOI+REu81aDvnOesq2jsHyDpqsZ+s8DwDIovA+ls=,tag:OYypDdTabI7KtoFo72FoPg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xFQkPOZun25piSWuu3gQQg==,iv:sYYefJwgCRmjsLtw8zTnbchYG76j+Ac5KFVfKWVuG60=,tag:qv1zaVvScmFClIRHGIb4YQ==,type:str]
type: ENC[AES256_GCM,data:aySL8Nut,iv:WKN+RLUQ1fKTu2hFys8foXBo934BtOJDpi5YZERlmLY=,tag:VNiorecuxvnw6wQkvyScyQ==,type:str]
data:
    username: ENC[AES256_GCM,data:+NeFJIwKrw==,iv:nAwnJ63rRxj4kWEFCAGtcqUp/Jqgm0VD4yELosRuqmY=,tag:umOSVpsFZEm6s9K3QlF+xw==,type:str]
    password: ENC[AES256_GCM,data:zqTLp4dH,iv:uTmhapGxy/I3aFZ3rqi0m1MrrVZACM4eE6JAiNo3LA8=,tag:dJSVkJV6q9zaiHbJnwv3nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-07T20:02:35Z"
    mac: ENC[AES256_GCM,data:SqJTfCeZZ3Deu6PukJTjc9Z7Uz5S+xVEEVLyFT7LiB0dVxpWVxpU3nd/08Vy/Dc1tt4r55tZAVtap/jU2/675GZcyR9pJOSnzWcXef+xDi1IM92tk1yehOpjnNzwWk1gpxWA+ZvEuvf/kSnfHOOiSk2b96isGjlM6SWNuz/MJmc=,iv:gL5dewQNhrCnrdDjyEAUvu2TwrwbdmE++gcGHscWGaM=,tag:/ACisCY1+0Vn2DaAVHtAbg==,type:str]
    pgp:
        - created_at: "2022-04-07T20:02:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAyUpShfNkFB/AQgAotONZ3+oqzVi/q9BPfwdncwHqNTzeXBmN7xbTd1d3UtK
            KVWQyOF8wXe5fsc8Di7l67BDZavjpV4wkV1POmAjn/KAApy2Q5+f2ygsnnr6k1wV
            EWQQd3A6d3W614Wf2xEfEBOR6Q0RV9XBeFRGETEM/Xqbehd/e5+JxHwo1DrAhSLW
            eNxAo0dWxUDCjvGPix7csrhQc/A7mXXuw5UYhT89gbD8AQD1X3sac5tc/ScK1Hi7
            BA6HKF7aFOuvMAKnHwy7qfOfxB6aHrS5AvU8wxt7P6+Y3h1HOvHxghP5a3jT8Dnh
            UabYm5PHbHBuP/g1RNQiVsqOluGXqjNHQpO0TuVrldJcAUjWDh/f+/VeoENDh4dH
            OQr1TRMUDOklhcmg5HAuXB26DvBab7GeSt2He6GCI2H9fY5odriG3btyX8IUJd2A
            mU3XofOI2P60+mgq0K7w4q898QIM1+JZctSleUg=
            =OC+D
            -----END PGP MESSAGE-----
          fp: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
        - created_at: "2022-04-07T20:02:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hIwDXFUltYFwV4MBBACNuyah8VHyaKWBsmZlSGojQcXI/5EZsaeTCmVWx9OCa+b+
            W82AoHVURJ0dxiKbgn1/Sfcs0WnGQHkrjysVLoxGpv1x6qeOg9XSeyhptDeKdLiy
            NSfM0HKOYLbAEf9PdRKoMmIlCoK/PsUvj1c7HWDx3XWH5fgoJWaYbmFBeBwJHtJc
            Ad3Mq0SId94KF74eS7EJRyVrWn1FXYAFyrvrhN71HL0bxRvyW2OUpN+zM+sq5tXn
            cD0B5jKgN/bjLubAehyIYnXAS2BkneShoabxqI9CInhqdRMJ9SKqByd2tMs=
            =TC7C
            -----END PGP MESSAGE-----
          fp: D7229043384BCC60326C6FB9D8720D957C3D3074
    unencrypted_suffix: _unencrypted
    version: 3.7.2
